# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "boot";
      fsType = "zfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/2D08-2DB1";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "tank/nixos/home/home";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "tank/nixos/home/root";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "tank/nixos/var";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "tank/nix";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/af6d4641-67b3-47a9-a0cc-0d0c2fb122f1"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = true;
}
