# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:
{
  boot.kernelPackages = pkgs.linuxPackages_4_19;

  boot.kernelParams = [ "cma=32M" ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };
  
  swapDevices = [ { device = "/swapfile"; size = 8192; } ];
}
